-- MySQL Script generated by MySQL Workbench
-- mer. 02 avril 2025 09:14:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema djepaxhk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema djepaxhk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `djepaxhk` ;
USE `djepaxhk` ;

-- -----------------------------------------------------
-- Table `djepaxhk`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djepaxhk`.`Media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `auteur` VARCHAR(45) NOT NULL,
  `editeur` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `dateParution` INT NOT NULL,
  `genre` VARCHAR(45) NULL,
  `nombreExemplaire` INT NULL,
  PRIMARY KEY (`idMedia`),
  UNIQUE INDEX `idMedia_UNIQUE` (`idMedia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djepaxhk`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djepaxhk`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djepaxhk`.`Emprunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djepaxhk`.`Emprunt` (
  `idEmprunt` INT NOT NULL AUTO_INCREMENT,
  `dateEmprunt` DATE NOT NULL,
  `dateRetour` DATE NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Media_idMedia` INT NOT NULL,
  PRIMARY KEY (`idEmprunt`),
  INDEX `fk_Emprunt_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Emprunt_Media1_idx` (`Media_idMedia` ASC) VISIBLE,
  UNIQUE INDEX `idEmprunt_UNIQUE` (`idEmprunt` ASC) VISIBLE,
  CONSTRAINT `fk_Emprunt_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `djepaxhk`.`Utilisateur` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Emprunt_Media1`
    FOREIGN KEY (`Media_idMedia`)
    REFERENCES `djepaxhk`.`Media` (`idMedia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
